### ISSUE TITLE
Replace cardfinder helper

### ISSUE THREAD

**Issue by jwoolley** [mdiehr/mtgnewsbot#65]
The cardfinder endpoint is not reliably returning images for cardnames, which is needed for many of our graphics headlines. Replacing this functionality with a native solution should improve reliability and remove an external dependency.

**Comment by mdiehr** [comment]
How would a solution native to the bot work? Would we need to download the images to some configurable image cache and then "link" to them in the svg/html?

**Comment by mdiehr** [comment]
I guess for this to work we'd need to post-process the svg/html somehow

**Comment by mdiehr** [comment]
fixed a couple days ago
