### ISSUE TITLE
Send notification when a tweet fails

### ISSUE THREAD

**Issue by jwoolley** [mdiehr/mtgnewsbot#72]
A riff on https://github.com/mdiehr/mtgnewsbot/issues/69:

It would be useful to get a notification when there's a failure when the shell script runs. Possibly as a discord message (with a link to the logs, if available).

**Comment by mdiehr** [comment]
Integrating this w/ discord is a good idea.
Some docs on this: https://support.discordapp.com/hc/en-us/articles/228383668-Intro-to-Webhooks
